from django.db import models
from django.utils import timezone

# Create your models here.
class Registered_Admin(models.Model):
    admin_id = models.AutoField(primary_key=True)
    mfirstname = models.CharField(max_length=250, default="")
    mmiddlename = models.CharField(max_length=250, default="")
    mlastname = models.CharField(max_length=250, default="")
    memail = models.CharField(max_length=250, default="")
    mpassword = models.CharField(max_length=250, default="")
    mcpassword = models.CharField(max_length=250, default="")
    mmobile = models.IntegerField(default="")
    mdob = models.DateField(default="")
    mqualification = models.CharField(max_length=150, default="")
    mfacilityname = models.CharField(max_length=150, default="")
    mstate = models.CharField(max_length=150, default="")
    mdistrict = models.CharField(max_length=150, default="")
    mcity = models.CharField(max_length=150, default="")
    mpincode = models.IntegerField(default="")
    manager_flag = models.IntegerField(default=0)
    mdatetime = models.DateTimeField(default=timezone.now)

class Patient_data(models.Model):
    patient_id = models.AutoField(primary_key=True)
    fullname = models.CharField(max_length=100, default=None, null=True, blank=True)
    email = models.CharField(max_length=1000, default=None, null=True, blank=True)
    password = models.CharField(max_length=1000, default=None, null=True, blank=True)
    age = models.IntegerField(max_length=10, default=None, null=True, blank=True)
    fulladdress = models.CharField(max_length=100, default=None, null=True, blank=True)
    gender = models.IntegerField(max_length=5, default=None, null=True, blank=True)
    chestpaintype = models.CharField(max_length=100, default=None, null=True, blank=True)
    glucosevalue = models.CharField(max_length=100, default=None, null=True, blank=True)
    bloodpressure = models.IntegerField(max_length=15, default=None, null=True, blank=True)
    insulinvalue = models.IntegerField(max_length=20, default=None, null=True, blank=True)
    bmi = models.CharField(max_length=50, default=None, null=True, blank=True)
    prediabetic = models.CharField(max_length=100, default=None, null=True, blank=True)
    dpf = models.CharField(max_length=100, default=None, null=True, blank=True)
    cholestrol = models.CharField(max_length=100, default=None, null=True, blank=True)
    dailyexercise = models.CharField(max_length=15, default=None, null=True, blank=True)
    sleepinghabits = models.CharField(max_length=100, default=None, null=True, blank=True)
    brushinghabits = models.CharField(max_length=100, default=None, null=True, blank=True)
    image = models.CharField(max_length=500, default=None, null=True, blank=True)
    about = models.CharField(max_length=500, default=None, null=True, blank=True)
    phone = models.CharField(max_length=50, default=None, null=True, blank=True)
    prescription = models.CharField(max_length=500, default=None, null=True, blank=True)
    otp = models.CharField(max_length=10, default=None, null=True, blank=True)
    image = models.FileField(upload_to='patients/images', default=None, null=True, blank=True)
    abha_id = models.CharField(max_length=200, default=None, null=True, blank=True)
    google_client_id = models.CharField(max_length=500, default=None, null=True, blank=True)
    google_secret_key = models.CharField(max_length=1000, default=None, null=True, blank=True)
    report = models.FileField(upload_to='patients/reports', default=None, null=True, blank=True)
    xray = models.FileField(upload_to='patients/xray', default=None, null=True, blank=True)
    esio_first_name = models.CharField(max_length=200, default=None, null=True, blank=True)
    esio_patient_name = models.CharField(max_length=200, default=None, null=True, blank=True)
    esio_folder_name = models.CharField(max_length=200, default=None, null=True, blank=True)
    threed = models.CharField(max_length=5, default=0)
    pdf = models.FileField(upload_to='patients/prescription', default=None, null=True, blank=True)
