from django.db import models
from django.utils import timezone

# Create your models here.
class Registered_Admin(models.Model):
    admin_id = models.AutoField(primary_key=True)
    mfirstname = models.CharField(max_length=250, default="")
    mmiddlename = models.CharField(max_length=250, default="")
    mlastname = models.CharField(max_length=250, default="")
    memail = models.CharField(max_length=250, default="")
    mpassword = models.CharField(max_length=250, default="")
    mcpassword = models.CharField(max_length=250, default="")
    mmobile = models.IntegerField(default="")
    mdob = models.DateField(default="")
    mqualification = models.CharField(max_length=150, default="")
    mfacilityname = models.CharField(max_length=150, default="")
    mstate = models.CharField(max_length=150, default="")
    mdistrict = models.CharField(max_length=150, default="")
    mcity = models.CharField(max_length=150, default="")
    mpincode = models.IntegerField(default="")
    manager_flag = models.IntegerField(default=0)
    mdatetime = models.DateTimeField(default=timezone.now)

class Patient_data(models.Model):
    patient_id = models.AutoField(primary_key=True)
    fullname = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    age = models.IntegerField(max_length=10)
    fulladdress = models.CharField(max_length=100)
    gender = models.IntegerField(max_length=5)
    chestpaintype = models.CharField(max_length=100)
    glucosevalue = models.CharField(max_length=100)
    bloodpressure = models.IntegerField(max_length=15)
    insulinvalue = models.IntegerField(max_length=20)
    bmi = models.CharField(max_length=50)
    prediabetic = models.CharField(max_length=100)
    dpf = models.CharField(max_length=100)
    cholestrol = models.CharField(max_length=100)
    dailyexercise = models.CharField(max_length=15)
    sleepinghabits = models.CharField(max_length=100)
    brushinghabits = models.CharField(max_length=100)
    image = models.CharField(max_length=500)
    about = models.CharField(max_length=500)
    phone = models.CharField(max_length=50)
    prescription = models.CharField(max_length=500)
    otp = models.CharField(max_length=10)