# Generated by Django 4.2.4 on 2023-09-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathologist', '0002_registered_pathologist_pconfirmpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_pathologist',
            name='pabout',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
    ]
