# Generated by Django 4.2.4 on 2023-09-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathologist', '0003_registered_pathologist_pabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_pathologist',
            name='pmobile',
            field=models.CharField(max_length=15),
        ),
    ]
