# Generated by Django 4.2.4 on 2023-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='watch_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50)),
                ('steps', models.CharField(max_length=50)),
                ('calories_burnt', models.CharField(max_length=50)),
                ('heart_minutes', models.CharField(max_length=50)),
            ],
        ),
    ]
