# Generated by Django 4.2.4 on 2023-09-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch_data',
            old_name='pid',
            new_name='patient_id',
        ),
    ]
