# Generated by Django 4.2.4 on 2023-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_pid_watch_data_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_data',
            name='patient_id',
            field=models.IntegerField(),
        ),
    ]
