# Generated by Django 4.2.4 on 2023-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_watch_data_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_data',
            name='date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
