# Generated by Django 4.2.4 on 2023-09-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_watch_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_data',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
