# Generated by Django 4.2.4 on 2023-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_watch_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_data',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
