# Generated by Django 4.2.4 on 2023-09-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_watch_data_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch_data',
            options={'ordering': ['date']},
        ),
    ]
