# Generated by Django 4.2.4 on 2023-09-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0016_patient_data_abha_id'),
        ('User', '0009_alter_watch_data_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='vitals_data',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('bodytemperature', models.IntegerField()),
                ('pulserate', models.CharField(max_length=50)),
                ('respiratoryrate', models.CharField(max_length=50)),
                ('bp', models.CharField(max_length=50)),
                ('spo2', models.IntegerField()),
                ('weight', models.CharField(max_length=50)),
                ('bloodsugarfbs', models.CharField(max_length=50)),
                ('bloodsugarrbs', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.patient_data')),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('datetime', 'vid', 'patient_id')},
            },
        ),
        migrations.CreateModel(
            name='todays_feel_data',
            fields=[
                ('today_id', models.AutoField(primary_key=True, serialize=False)),
                ('bodyache_duration', models.CharField(max_length=20)),
                ('bodyache_occurance', models.CharField(max_length=20)),
                ('allergy_duration', models.CharField(max_length=20)),
                ('allergy_occurance', models.CharField(max_length=20)),
                ('backpain_duration', models.CharField(max_length=20)),
                ('backpain_occurance', models.CharField(max_length=20)),
                ('headache_duration', models.CharField(max_length=20)),
                ('headache_occurance', models.CharField(max_length=20)),
                ('dental_pain_duration', models.CharField(max_length=20)),
                ('dental_pain_occurance', models.CharField(max_length=20)),
                ('acidity_duration', models.CharField(max_length=20)),
                ('acidity_occurance', models.CharField(max_length=20)),
                ('stomachache_duration', models.CharField(max_length=20)),
                ('stomachache_occurance', models.CharField(max_length=20)),
                ('common_cold_duration', models.CharField(max_length=20)),
                ('common_cold_occurance', models.CharField(max_length=20)),
                ('vomiting_duration', models.CharField(max_length=20)),
                ('vomiting_occurance', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.patient_data')),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('today_id', 'datetime', 'patient_id')},
            },
        ),
        migrations.CreateModel(
            name='health_condition_data',
            fields=[
                ('hcid', models.AutoField(primary_key=True, serialize=False)),
                ('diabetes', models.IntegerField()),
                ('obesity', models.IntegerField()),
                ('cancer', models.IntegerField()),
                ('heart_disease', models.IntegerField()),
                ('stroke', models.IntegerField()),
                ('mental_health', models.IntegerField()),
                ('asthama', models.IntegerField()),
                ('hearing_loss', models.IntegerField()),
                ('arthritis', models.IntegerField()),
                ('post_traumatic_stress_disorder', models.IntegerField()),
                ('hiv_aids', models.IntegerField()),
                ('gastrointestinal_disorder', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.patient_data')),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('hcid', 'datetime', 'patient_id')},
            },
        ),
    ]
