# Generated by Django 4.2.4 on 2023-09-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_medication_data_exercise_data_eating_habits_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication_data',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='medication_data',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medication_data',
            name='patient_id',
        ),
    ]
