# Generated by Django 4.2.4 on 2023-09-29 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0018_patient_data_report_patient_data_xray'),
        ('User', '0012_alter_medication_data_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication_data',
            options={'ordering': ['datetime']},
        ),
        migrations.AddField(
            model_name='medication_data',
            name='patient_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Manager.patient_data'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='medication_data',
            unique_together={('med_id', 'datetime', 'patient_id')},
        ),
    ]
