# Generated by Django 4.2.4 on 2023-09-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_medication_data_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eating_habits_data',
            name='ddosa',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
    ]
