# Generated by Django 4.2.4 on 2023-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_eating_habits_data_ddosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eating_habits_data',
            name='baloogobi',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='bbchicken',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='bbiryani',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='bchickencurry',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='bchole',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='bdal',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='bjeerarice',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='bmixveg',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='btikka',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='daloogobi',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dbhature',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dbutterchecken',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dchole',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='ddosa',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='didli',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dmeduvada',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dmixveg',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dpoha',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dpoori',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dsamosa',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dtikka',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='dupma',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='laloogobi',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lalooparatha',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lbhature',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lbutterchicken',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lchole',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='ldosa',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lidli',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lmeduvada',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lpoha',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lpoori',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lsamosa',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='eating_habits_data',
            name='lupma',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
