# Generated by Django 4.2.4 on 2023-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_health_condition_data_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_condition_data',
            name='arthritis',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='asthama',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='cancer',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='gastrointestinal_disorder',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='hearing_loss',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='heart_disease',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='hiv_aids',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='mental_health',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='obesity',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='post_traumatic_stress_disorder',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='health_condition_data',
            name='stroke',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
