# Generated by Django 4.2.4 on 2023-09-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0018_patient_data_report_patient_data_xray'),
        ('User', '0018_alter_health_condition_data_arthritis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eating_habits_other',
            fields=[
                ('other_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('breakfast', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('lunch', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('dinner', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.patient_data')),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('patient_id', 'datetime', 'other_id')},
            },
        ),
    ]
