# Generated by Django 4.2.4 on 2023-09-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_eating_habits_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='eating_habits_other',
            name='high_tea',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
