# Generated by Django 4.2.4 on 2023-10-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0022_patient_data_pdf'),
        ('User', '0020_eating_habits_other_high_tea'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription_data',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('prescription', models.FileField(max_length=200, upload_to='')),
                ('datetime', models.DateTimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.patient_data')),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('patient_id', 'datetime', 'pres_id')},
            },
        ),
    ]
