# Generated by Django 4.2.4 on 2023-10-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0022_patient_data_pdf'),
        ('User', '0021_prescription_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='iglu_data',
            fields=[
                ('iglu_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('glucoserbs', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.patient_data')),
            ],
            options={
                'ordering': ['datetime'],
                'unique_together': {('iglu_id', 'patient_id', 'datetime')},
            },
        ),
    ]
