# Generated by Django 4.2.4 on 2023-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True)),
                ('dfirstname', models.CharField(max_length=150)),
                ('dmiddlename', models.CharField(max_length=150)),
                ('dlastname', models.CharField(max_length=150)),
                ('ddob', models.CharField(max_length=150)),
                ('dmobile', models.IntegerField()),
                ('demail', models.CharField(max_length=50)),
                ('dregistrationcouncil', models.CharField(max_length=150)),
                ('dothercouncil', models.CharField(default=None, max_length=150)),
                ('dregistrationnumber', models.CharField(max_length=150)),
                ('dqualification', models.CharField(max_length=70)),
                ('duniversityname', models.CharField(max_length=150)),
                ('dpassingyear', models.IntegerField()),
                ('dclinicname', models.CharField(max_length=150)),
                ('dstate', models.CharField(max_length=150)),
                ('ddistrict', models.CharField(max_length=200)),
                ('dcity', models.CharField(max_length=200)),
                ('dpincode', models.IntegerField()),
                ('dtestfacility', models.CharField(max_length=150)),
                ('ddatetime', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('doctorflag', models.IntegerField()),
            ],
        ),
    ]
