# Generated by Django 4.2.4 on 2023-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_alter_registered_doctor_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_doctor',
            name='doctor_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
