# Generated by Django 4.2.4 on 2023-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_alter_registered_doctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_doctor',
            name='dabout',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
    ]
