# Generated by Django 4.2.4 on 2023-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('username', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
