# Generated by Django 4.2.4 on 2023-08-30 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_data',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('fulladdress', models.CharField(max_length=100)),
                ('gender', models.IntegerField(max_length=5)),
                ('chestpaintype', models.CharField(max_length=100)),
                ('glucosevalue', models.CharField(max_length=100)),
                ('bloodpressure', models.IntegerField(max_length=15)),
                ('insulinvalue', models.IntegerField(max_length=20)),
                ('bmi', models.CharField(max_length=50)),
                ('prediabetic', models.CharField(max_length=100)),
                ('dpf', models.CharField(max_length=100)),
                ('cholestrol', models.CharField(max_length=100)),
                ('dailyexercise', models.CharField(max_length=15)),
                ('sleepinghabits', models.CharField(max_length=100)),
                ('brushinghabits', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('mfirstname', models.CharField(default='', max_length=250)),
                ('mmiddlename', models.CharField(default='', max_length=250)),
                ('mlastname', models.CharField(default='', max_length=250)),
                ('memail', models.CharField(default='', max_length=250)),
                ('mpassword', models.CharField(default='', max_length=250)),
                ('mcpassword', models.CharField(default='', max_length=250)),
                ('mmobile', models.IntegerField(default='')),
                ('mdob', models.DateField(default='')),
                ('mqualification', models.CharField(default='', max_length=150)),
                ('mfacilityname', models.CharField(default='', max_length=150)),
                ('mstate', models.CharField(default='', max_length=150)),
                ('mdistrict', models.CharField(default='', max_length=150)),
                ('mcity', models.CharField(default='', max_length=150)),
                ('mpincode', models.IntegerField(default='')),
                ('manager_flag', models.IntegerField(default=0)),
                ('mdatetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
