# Generated by Django 4.2.4 on 2023-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('fulladdress', models.CharField(max_length=100)),
                ('gender', models.IntegerField(max_length=5)),
                ('chestpaintype', models.CharField(max_length=100)),
                ('glucosevalue', models.CharField(max_length=100)),
                ('bloodpressure', models.IntegerField(max_length=15)),
                ('insulinvalue', models.IntegerField(max_length=20)),
                ('bmi', models.CharField(max_length=50)),
                ('prediabetic', models.CharField(max_length=100)),
                ('dpf', models.CharField(max_length=100)),
                ('cholestrol', models.CharField(max_length=100)),
                ('dailyexercise', models.CharField(max_length=15)),
                ('sleepinghabits', models.CharField(max_length=100)),
                ('brushinghabits', models.CharField(max_length=100)),
            ],
        ),
    ]
