# Generated by Django 4.2.4 on 2023-09-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_patient_data_about_patient_data_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
