# Generated by Django 4.2.4 on 2023-08-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_user_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_data',
            new_name='Patient_data',
        ),
    ]
