# Generated by Django 4.2.4 on 2023-08-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_rename_user_data_patient_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_data',
            old_name='user_id',
            new_name='patient_id',
        ),
    ]
