# Generated by Django 4.2.4 on 2023-08-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_rename_user_id_patient_data_patient_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_data',
            new_name='Registered_Admin',
        ),
    ]
