# Generated by Django 4.2.4 on 2023-09-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_alter_patient_data_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='prescription',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
    ]
