# Generated by Django 4.2.4 on 2023-09-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_patient_data_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='otp',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
