# Generated by Django 4.2.4 on 2023-09-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_patient_data_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
