# Generated by Django 4.2.4 on 2023-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_alter_patient_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='image',
            field=models.FileField(default='', upload_to='patients/image'),
        ),
    ]
