# Generated by Django 4.2.4 on 2023-09-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0013_alter_patient_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='password',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
