# Generated by Django 4.2.4 on 2023-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0014_patient_data_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_data',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
