# Generated by Django 4.2.4 on 2023-09-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0015_alter_patient_data_email_alter_patient_data_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='abha_id',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
    ]
