# Generated by Django 4.2.4 on 2023-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0017_patient_data_google_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='report',
            field=models.FileField(default='', upload_to='patients/reports'),
        ),
        migrations.AddField(
            model_name='patient_data',
            name='xray',
            field=models.FileField(default='', upload_to='patients/xray'),
        ),
    ]
