# Generated by Django 4.2.4 on 2023-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0021_patient_data_threed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='patients/prescription'),
        ),
    ]
